sudo: false
language: node_js
node_js:
  - 14.17.0
cache: yarn
branches:
  only:
    - main # build master branch only
script:
  - hexo generate # generate static files
  # 注意这个main
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: main
  local-dir: public